### ISSUE TITLE
Doesn't work well with HIDPI under Linux

### ISSUE THREAD

**Issue by thorhop** [flaviotordini/musique#1]
When using a HIDPI/retina screen (3200x1800) the album thumbnails are to small, the numbering in the playlist viewer collides with song titles, the main menu items are cropped since the font won't fit inside the main menu frame and transport control buttons are very small indeed.

**Comment by flaviotordini** [comment]
I don't have a HiDPI Linux to test with. I guess Qt4 is unaware of "logical" pixels. I'll soon port Musique to Qt5 and that will probably fix this.

**Comment by flaviotordini** [comment]
Fixed in 1.5 which is based on Qt 5 and has hidpi support
