### ISSUE TITLE
Shortcuts to Play/Pause and skip to next song if in different app

### ISSUE THREAD

**Issue by jancborchardt** [flaviotordini/musique#11]
Oftentimes when Musique is in the background I’d like to switch the song or pause/play. For that I need to switch to the Musique window which is a big context switch.

It would be cool if there would be keyboard shortcuts you could use globally, if possible, while you are focused in another app.

**Comment by flaviotordini** [comment]
Musique supports media keys. Play/Stop/Next/Prev.

**Comment by meradoou** [comment]
Media keys doesn't work with Musique on Windows 10
