### ISSUE TITLE
http://musicbrainz.org/ws/1/ will cease to exist soon

### ISSUE THREAD

**Issue by mwiencek** [flaviotordini/musique#17]
https://blog.metabrainz.org/2018/02/01/web-service-ver-1-0-ws-1-will-be-removed-in-6-months/

That didn't happen in August, but will likely happen soon. It should be relatively straightforward to adapt the code to use https://wiki.musicbrainz.org/Development/XML_Web_Service/Version_2

**Comment by flaviotordini** [comment]
It's not actually used. Will remove the unused code.
