### ISSUE TITLE
Compiling from scratch errors

### ISSUE THREAD

**Issue by bracca95** [flaviotordini/musique#24]
I tried to clone the repo and compile it by following the `README.md` file. I found and solved some issues. I have not commited what I am going to explain, so I will only describe **where** I found the errors and **how** I solved them.
Please consider fixing them, if necessary, in a future commit.

On Debian 10 (buster):

Problem 1)
There are a couple of missing files:
* `musique/lib/media/src/mpv/client.h`
* `musique/lib/media/src/mpv/qthelper.h`

Problem 2)
Incorrect path in file `musique/src/model/artist.cpp`
* reference to non existing header `"imagedownloader.h"`

Problem 3)
In the `README.md` file, the libraries to be installed before cloning the repository are incomplete.

-----------------

Solution 1)
Please refer to this link and copy paste the missing file in the specified folder:
https://github.com/mpv-player/mpv/tree/master/libmpv

Solution 2)
The file is present, yet not correctly linked. Replace:
`"imagedownloader.h"` --> `"../imagedownloader.h"`

Solution 3)
Here is a sample command to install the libraries needed
`sudo apt install build-essential qttools5-dev-tools qt5-qmake libphonon4qt5-dev libqt5sql5-sqlite qt5-default libtag1-dev libmpv-dev qml-module-qt-labs-platform mpv`

**Comment by lightdarkx** [comment]
Don't know why the issue didn't get fixed yet. Was able to install the app in ubuntu 18.04.3 after following your instructions.

**Comment by flaviotordini** [comment]
Problem 1 is invalid: you should clone as specified in the README and you will have the files.
2. I'll look into it.
3. No, the libs you list are wrong and not needed
