### ISSUE TITLE
Musique not working on latest version of Debian 10

### ISSUE THREAD

**Issue by SuperDuperUser** [flaviotordini/musique#26]
Today, I downloaded and installed Musique onto my Debian 10 desktop. I used the .DEB package that is provided on the project's home page. However, when I try to run Musique, it returns this error:

``musique: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by Musique)``

I believe this is happening because the latest version of Qt available on Debian 10 is 5.11.3. This can be seen on Debian's repo pages when searching for qt5: https://packages.debian.org/search?suite=buster&arch=any&searchon=names&keywords=qt5

Is it possible to rebuild the .DEB package but using Qt 5.11.3 instead, or does Musique rely on something only present in 5.12?

**Comment by flaviotordini** [comment]
I build on the latest Ubuntu LTS. It's impossible to be always compatible with the aging Debian stable version. I'm also using Qt 5.12 features so I'm just closing this.
