### ISSUE TITLE
Compilation error on Mageia Cauldron x86_64

### ISSUE THREAD

**Issue by kekePower** [flaviotordini/musique#33]
Build log here: https://raw.githubusercontent.com/kekePower/mmbl/036267c164253066da8fbe3534d02d69e2699644/2020/10/06/19%3A21%3A54/musique-1.10-1.mga8.src.rpm/build.0.20201006171853.log

Qt version: 5.15.1
GCC 10.2.0

Is there anything else you need to know?

**Comment by darkshram** [comment]
Have same issue with custom distro. Qt5 5.12.9, gcc-c++ 7.3.1.

[https://pastebin.com/v4XkCBhX](https://pastebin.com/v4XkCBhX)

Last built and working version for me was 1.7. I can't build musique since 1.8.

**Comment by kekePower** [comment]
This simple fix worked for me. Have no idea if it's the right one.

```diff
Index: musique-1.10/src/mainwindow.cpp
===================================================================
--- musique-1.10/src/mainwindow.cpp
+++ musique-1.10/src/mainwindow.cpp	2020-10-06 20:22:28.615273826 +0200
@@ -1312,8 +1312,6 @@
     return;
 #endif
 
-    const QString baseUrl = QLatin1String("https://") + Constants::ORG_DOMAIN;
-
 #ifdef APP_EXTRA
     const QString filesUrl = baseUrl + QLatin1String("/files/");
     QString url = filesUrl + "finetune/finetune.";
```

**Comment by darkshram** [comment]
@kekePower: Builds and runs Ok.

**Comment by flaviotordini** [comment]
Thanks, I made a mess with pull requests.
