### ISSUE TITLE
Stuck at 0% when scanning music folder on Windows 10

### ISSUE THREAD

**Issue by zenfunkpanda** [flaviotordini/musique#35]
The same latest version on Windows 7 runs perfectly, on Windows 10 give that error (via WinDbg):

```
[unknown] Update check failed 0 ""
[unknown] QSslSocket::connectToHostEncrypted: TLS initialization failed
[unknown] Discogs error, retrying... "Album Name" ""
```

**Comment by flaviotordini** [comment]
Looks like something is wrong with TLS so Musique cannot make HTTPS calls. I'll have a look.

**Comment by flaviotordini** [comment]
I believe Musique setup is missing msvcr100.dll which is usually found in most Windows installations but probably not yours. I will fix the setup. In the meantime install this:

https://www.microsoft.com/en-US/Download/confirmation.aspx?id=14632
