### ISSUE TITLE
Add an RPM

### ISSUE THREAD

**Issue by franktopel** [flaviotordini/musique#39]
> This is for packagers. End users should not install applications in this way.

So what am I supposed to do if I want to run this application on Fedora 34?

**Comment by arobertson404** [comment]
Musique compiles in Fedora 35:

sudo dnf install qt5-qtbase-devel qt5-qttools-devel qt5-qtdeclarative-devel taglib-devel mpv-libs-devel
git clone --recursive https://github.com/flaviotordini/musique.git
cd musique
qmake-qt5
make
sudo make install

It would be nice to see it in the repos though!

**Comment by flaviotordini** [comment]
Well, tell that to Fedora people!
