### ISSUE TITLE
Icon Theme?

### ISSUE THREAD

**Issue by Teknocrat** [flaviotordini/musique#4]
I see you have icons in your images/ folder, but they do not appear to be installed by `make install`
which icon theme do you test against?
I have Faenza, Hicolor and Adwaita and Icons fail to load

This is release build 1.4 on Gentoo x64

**Comment by Teknocrat** [comment]
![2015-09-24-031139_373x207_scrot](https://cloud.githubusercontent.com/assets/2731786/10070869/26a9025c-626a-11e5-9d25-38b24f7b9f97.png)

**Comment by flaviotordini** [comment]
On Linux, Musique uses QIcon::fromTheme. If icons do not load it's a Qt or distro bug/limitation.

**Comment by Teknocrat** [comment]
Well since i maintaining your packages on gentoo do you mind answering my other questions..
What icon suite do you use / build against? Your icon names your using in your code are deprecated gtk2 names no longer supported in modern icon suits... You should really be using newer names or else others will have this issue on their distros...

**Comment by flaviotordini** [comment]
Can you give an example of deprecated icon names. I'm not aware of any change in free desktop icon names.
