### ISSUE TITLE
Did you release version 1.11 or just tagged it?

### ISSUE THREAD

**Issue by kekePower** [flaviotordini/musique#45]
Just out of curiousity.

Saw a message back in February about version 1.11 and am wondering if you meant to release this version or if you're just preparing for a release.

Thanks.

**Comment by brad0** [comment]
> Just out of curiousity.
> 
> Saw a message back in February about version 1.11 and am wondering if you meant to release this version or if you're just preparing for a release.

I was wondering that myself as I saw bumps in the repo for 1.10.2 and 1.11 but no tags.

**Comment by flaviotordini** [comment]
It's not released. It's not tagged. I was just preparing for a Qt6 based release.
