### ISSUE TITLE
libtag1c2a is not installable

### ISSUE THREAD

**Issue by pedzed** [flaviotordini/musique#5]
I am using Ubuntu 16.04 and I cannot install Musique.

```
musique : Depends: libtag1c2a but it is not installable
```

It seems to be obsolete:
http://packages.ubuntu.com/search?keywords=libtag1c2a

**Comment by flaviotordini** [comment]
I'm aware of the issue and will fix it for the next Musique release. In the meantime you can build by yourself or use the Ubuntu provided package.

**Comment by flaviotordini** [comment]
1.5 is coming, closing now
