### ISSUE TITLE
Compatibility with TagLib 2.0

### ISSUE THREAD

**Issue by letsfindaway** [flaviotordini/musique#53]
With TagLib 2.0 released on 24.01.2024, some incompatible API changes have been introduced. For `musique` this means that it currently does not compile with TagLib 2.0.

As far as I have seen the only incompatibility affecting `musique` is renaming of `MP4::Tag::ItemListMap` to `ItemMap`. If I change that, then it compiles and runs.

Are there any plans to make the source code compile with TagLib 2.0?

**Comment by flaviotordini** [comment]
Thanks, I didn't try TagLib 2. If you make a pull request without breaking taglib 1 I would merge it right away.

**Comment by letsfindaway** [comment]
`ItemMap` was added and `ItemListMap` deprecated with TagLib 1.10 which was released 9 years ago (4.10.2015):

https://github.com/taglib/taglib/blob/9f697fce8e287d6720cb37d5ee6e30eeccb9fb9c/taglib/mp4/mp4tag.h#L42-L46

So my PR would break compatibility with TagLib < 1.10, but I think this is acceptable as you now require Qt 6.

I will provide a PR tomorrow.
