### ISSUE TITLE
Can't compile on Arch

### ISSUE THREAD

**Issue by AcarBurak** [flaviotordini/musique#6]
src/tags/tagutils.cpp:2:31: fatal error: collectionscanner.h: No such file or directory
 #include "collectionscanner.h"
                               ^
compilation terminated.
make: **\* [Makefile:1432: build/obj/tagutils.o] Error 1

**Comment by GinoM** [comment]
Looks like he started working on this and never finished?? anyway attached is a patch to fix this build, it I got it to compile fine against qt 5.6.2

`diff -ru two/musique.pro flaviotordini_musique/musique.pro
--- two/musique.pro	2016-12-09 00:05:33.857768933 -0800
+++ flaviotordini_musique/musique.pro	2016-12-09 00:19:50.241791866 -0800
@@ -16,9 +16,10 @@
 
 TARGET = $${APP_UNIX_NAME}
 
-QT += network sql widgets
+QT += network sql widgets 
+
+CONFIG += qtsingleapplication
 
-include(src/qtsingleapplication/qtsingleapplication.pri)
 include(src/http/http.pri)
 include(src/tags/tags.pri)
 
diff -ru two/src/aboutview.cpp flaviotordini_musique/src/aboutview.cpp
--- two/src/aboutview.cpp	2016-12-09 00:05:33.857768933 -0800
+++ flaviotordini_musique/src/aboutview.cpp	2016-12-09 00:27:58.018804928 -0800
@@ -73,8 +73,8 @@
             .arg("<a href='http://www.transifex.net/projects/p/" + QLatin1String(Constants::UNIX_NAME) + "/'>Transifex</a>") + "</p>";
 
 #ifndef APP_EXTRA
-    "<p>" + tr("Released under the <a href='%1'>GNU General Public License</a>")
-    .arg("http://www.gnu.org/licenses/gpl.html") + "</p>"
+    info += "<p>" + tr("Released under the <a href='%1'>GNU General Public License</a>")
+	.arg("http://www.gnu.org/licenses/gpl.html") + "</p>";
 #endif
 
     info += "<p>&copy; 2016 " + QLatin1String(Constants::ORG_NAME) + "</p></body></html>";
diff -ru two/src/appwidget.cpp flaviotordini_musique/src/appwidget.cpp
--- two/src/appwidget.cpp	2016-12-09 00:05:33.858768933 -0800
+++ flaviotordini_musique/src/appwidget.cpp	2016-12-09 00:37:08.860819680 -0800
@@ -1,7 +1,9 @@
 #include "appwidget.h"
 #include "constants.h"
 #include "http.h"
+#ifdef APP_EXTRA
 #include "updatedialog.h"
+#endif
 
 AppsWidget::AppsWidget(QWidget *parent) : QWidget(parent) {
     const int padding = 30;
@@ -17,8 +19,9 @@
     const QString ext = "exe";
 #elif defined APP_UBUNTU
     const QString ext = "deb";
+#else
+    const QString ext = "";
 #endif
-
     setupApp("Finetune", "finetune." + ext);
     setupApp("Minitube", "minitube." + ext);
     setupApp("Musictube", "musictube." + ext);
@@ -102,7 +105,9 @@
 }
 
 void AppWidget::downloadApp() {
+#ifdef APP_EXTRA    
     UpdateDialog *dialog = new UpdateDialog(icon->pixmap(), name, QString(), url, this);
     dialog->downloadUpdate();
     dialog->show();
+#endif
 }
diff -ru two/src/choosefolderview.cpp flaviotordini_musique/src/choosefolderview.cpp
--- two/src/choosefolderview.cpp	2016-12-09 00:05:33.859768933 -0800
+++ flaviotordini_musique/src/choosefolderview.cpp	2016-12-09 00:29:43.788807761 -0800
@@ -99,7 +99,7 @@
                     .arg(Constants::NAME) + " " +
                     tr("If you have privacy concerns about this you can quit now.")
                     , this);
-    privacyLabel->setFont(FontUtils::smaller());
+    privacyLabel->setFont(FontUtils::small());
     privacyLabel->setOpenExternalLinks(true);
     privacyLabel->setWordWrap(true);
     vLayout->addWidget(privacyLabel);
diff -ru two/src/mainwindow.cpp flaviotordini_musique/src/mainwindow.cpp
--- two/src/mainwindow.cpp	2016-12-09 00:05:33.867768933 -0800
+++ flaviotordini_musique/src/mainwindow.cpp	2016-12-09 00:26:26.268802471 -0800
@@ -1261,7 +1261,6 @@
 #if defined APP_MAC || defined APP_WIN
     if (Extra::runFinetune(filename)) return;
 #else
-    QStringList files = stats.value("filesNeedingFix").toStringList();
     QProcess process;
     if (process.startDetached("finetune", QStringList(filename)))
         return;
@@ -1279,9 +1278,11 @@
 #endif
     url += ext;
     QPixmap pixmap = IconUtils::pixmap(":/images/64x64/finetune.png");
+#ifdef APP_EXTRA 
     UpdateDialog *dialog = new UpdateDialog(&pixmap, "Finetune", QString(), url, this);
     dialog->downloadUpdate();
     dialog->show();
+#endif
 }
 
 QString MainWindow::playlistPath() {
diff -ru two/src/tags/tags.pri flaviotordini_musique/src/tags/tags.pri
--- two/src/tags/tags.pri	2016-12-09 00:05:33.872768933 -0800
+++ flaviotordini_musique/src/tags/tags.pri	2016-12-09 00:11:32.037778525 -0800
@@ -1,10 +1,11 @@
 CONFIG -= rtti_off
 QMAKE_CXXFLAGS -= -fno-rtti
 
-INCLUDEPATH += $$PWD
+INCLUDEPATH += $$PWD $$PWD/..
 DEPENDPATH += $$PWD
 
 HEADERS += \
+    $$PWD/../collectionscanner.h \
     $$PWD/apeutils.h \
     $$PWD/asfutils.h \
     $$PWD/id3utils.h \
`

**Comment by GinoM** [comment]
Unfortunately it compiles but segfaults after it finishes media scan

**Comment by flaviotordini** [comment]
Should be fixed by now
