### ISSUE TITLE
Misalignment of playlist text

### ISSUE THREAD

**Issue by jancborchardt** [flaviotordini/musique#7]
Check this out:
![musique alignment](https://cloud.githubusercontent.com/assets/925062/23217549/f7e88b02-f919-11e6-8250-7170ad05db98.png)

The track names are ~10px further to the left than the artist name. It would look a lot cleaner if it would be aligned left the same.

**Comment by flaviotordini** [comment]
Yes, I concur. I will definitely make this change. Thanks.
