### ISSUE TITLE
Notifications for songs seem to be permanent

### ISSUE THREAD

**Issue by jancborchardt** [flaviotordini/musique#8]
After listening to a bunch of songs, I am faced with this:
![musique notifications](https://cloud.githubusercontent.com/assets/925062/23218328/49267c3e-f91c-11e6-842f-f6223c2ca28a.png)

Is there no way to remove the notification after the song is over?

**Comment by gitbreaker222** [comment]
I've noticed the same issue: Notifications-list gets flooded with songs. This behaviour has two negative aspects:

- Sending a notification about the song that just started playing, is usually redundant: I hear it already :speaker: :ear: 
- Notifications should inform the user of events, that deserve more attention. If an application floods the notification list with less important information, it becomes spam :space_invader: 

On the other hand I see two use-cases, that are currently handled by the notification-system:

- I want to know what is currently playing *(in screenshot above: You Can Dance)*
- I want to know what has been played in the past *(in screenshot above: e.g. Hella Good)*

Both may be better handled in the application itself. But removing existing features can also be harmful for good UX, so we could simply add a feature-toggle to the menu like in this sketch:

![Bildschirmfoto vom 2019-11-24 14-35-14](https://user-images.githubusercontent.com/4787651/69495596-01d25b80-0ec9-11ea-8efe-3f1b4374f32c.png)

*...the "played in past" would then be another playlist-feature*

**Comment by gitbreaker222** [comment]
I would like to see this feature so much, I've started imagine a donation page for it. And because I can edit HTML :smiley_cat:, I did this little mockup [(original source)](https://www.betterplace.me/true-development)

![2019-11-24_15-44-04_mockup feature request donate](https://user-images.githubusercontent.com/4787651/69496365-bc665c00-0ed1-11ea-9695-18e45a37503b.png)

@flaviotordini would this way of community support for non-coders cast a spark?

**Comment by flaviotordini** [comment]
@gitbreaker222 Thanks for your creativity ;) Yes, I should setup some sort of bug-funding and see if people are interested.

**Comment by flaviotordini** [comment]
I believe there is no way to have notifications expire. The man page for the notify-send command line utility state that:

> -t, --expire-time=TIME
>               The duration, in milliseconds, for the notification to appear on screen.  (Ubuntu's Notify OSD and GNOME Shell both ignore this parameter.)

**Comment by gitbreaker222** [comment]
thanks for your time looking into the notifications settings @flaviotordini. I think it is worth a try, as gnome is constantly evolving *(just updated to ubuntu 19.10 and the UI has improved again :)*

I also did a search on notifications and discovered, that they [can be turned off manually](https://help.gnome.org/users/gnome-help/stable/shell-notifications.html.en). @jancborchardt Maybe this helps, if the issue still persists for you after 2 years :smile: 

![2019-12-10_ 10-19-33 settings notifications](https://user-images.githubusercontent.com/4787651/70516226-ef962580-1b36-11ea-93ac-291ba83ad5da.png)
